#1 Prepare
- name: Create Ghost User
  user:
    name: ghost
    shell: /usr/sbin/nologin
    
- name: Create Ghost directory
  file:
    path: /data/wwwroot/ghost
    state: directory
    owner: ghost
    group: ghost

#2 Install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Copy docker-compose.yml and config.production.json
  template:
    src: "{{item}}"
    dest: /data/wwwroot/ghost/{{item}}
  loop:
    - docker-compose.yml
    - config.production.json

- name: Run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data/wwwroot/ghost

#3 Configure


#4 Verify
